### ISSUE TITLE
Add a penalize_diagonal boolean

### ISSUE THREAD

**Issue by jchiquet** [JClavel/glassoFast#1]
Hi @JClavel  and thank you for sharing.

I have been using the glasso package for a long time, but I am about to switching to yours because it seems to be a lot ore stable than the original one.

I was wondering how you were dealing with the penalty on the diagonal terms of the empirical covariance:  in the glasso package, it is possible to unpenalize the diagonal (that is, the conditional variances, which seems pretty fair from the statistical point of view).

Was is your choice in your package ? Do you penalize the diagonal or not ?

**Comment by JClavel** [comment]
Hi Julien,

If you don't want to penalize the diagonal terms, you can simply provide a matrix with the required structure for the regularization parameter:

e.g. (with the example given in ?glassoFast)
# With diagonal constraint
rhoMat <- matrix(0.1, p, p)
diag(rhoMat) <- 0

glassoFast(s, rho=rhoMat)
glasso(s, rho=0.1, penalize.diagonal=FALSE) # glasso implementation

HTH,

Julien


________________________________
De : Julien Chiquet <notifications@github.com>
Envoyé : mardi 16 octobre 2018 14:50
À : JClavel/glassoFast
Cc : JClavel; Mention
Objet : [JClavel/glassoFast] Add a penalize_diagonal boolean (#1)


Hi @JClavel<https://github.com/JClavel> and thank you for sharing.

I have been using the glasso package for a long time, but I am about to switching to yours because it seems to be a lot ore stable than the original one.

I was wondering how you were dealing with the penalty on the diagonal terms of the empirical covariance: in the glasso package, it is possible to unpenalize the diagonal (that is, the conditional variances, which seems pretty fair from the statistical point of view).

Was is your choice in your package ? Do you penalize the diagonal or not ?

**Comment by jchiquet** [comment]
Ok, thank you. Next time I will be reading the manual in details ;-)
